-- Manifestes des runs : configuration, versions, machine.
select
    run_id,
    model_key,
    model_display_name,
    model_quant,
    model_size_bytes,
    instance_identifier,
    context_length,
    parallel,
    prompt_variant::varchar as prompt_variant,
    variant_label,
    prompt_version,
    reasoning_mode::varchar as reasoning_mode,
    transport::varchar      as transport,
    generation_params,
    lmstudio_version,
    runtime_engine,
    python_version,
    package_version,
    git_sha,
    dataset_sha256,
    sample_spec,
    n_questions_planned,
    n_questions_done,
    n_errors,
    warmup_time_s,
    context_length_end,
    parallel_end,
    instance_identifier_end,
    config_changed,
    machine,
    started_at,
    finished_at,
    status
from {{ source('silver', 'runs') }}
