-- Reponses notees, toutes partitions de run confondues.
select
    run_id,
    question_id,
    model_key,
    model_quant,
    prompt_variant::varchar   as prompt_variant,
    prompt_version,
    reasoning_mode::varchar   as reasoning_mode,
    transport::varchar        as transport,
    prompt_sha256,
    ai_answer,
    ai_reasoning,
    predicted_letter,
    predicted_text,
    ai_correct,
    grade::varchar            as grade,
    grade_score::double       as grade_score,
    response_time::double     as response_time,
    ttft_s::double            as ttft_s,
    tokens_per_second::double as tokens_per_second,
    prompt_tokens::integer    as prompt_tokens,
    completion_tokens::integer as completion_tokens,
    reasoning_tokens::integer as reasoning_tokens,
    max_tokens::integer       as max_tokens,
    finish_reason,
    run_order::integer        as run_order,
    attempt::tinyint          as attempt,
    called_at,
    error
from {{ source('silver', 'answers') }}
